version: "3.8"
services:
    nginx:
        image: camofur/ngnix-load:1.0
        restart: always
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"

    frontend:
        image: camofur/frontend:1.0
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WDS_SOCKET_PORT=0

    backend:
        image: camofur/backend:1.0
        env_file:
            - ./backend/.env